### ISSUE TITLE
Lightbox gallery left and right arrows don't work in Thanks Roy

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#9]
The carousel arrows in the Lightbox don't respond to clicks, only in Thanks Roy:

![lightbox](https://github.com/omeka-s-themes/thanksroy/assets/28012148/7e194888-6ad0-43b0-bd20-015f1fa2f6ec)

It works fine in other themes. If you inspect in browser, the code does change (and you can see the icon or cursor change in some cases) but nothing actually advances.

**Comment by allanaaa** [comment]
Turns out the left and right arrows aren't working in the timeline either:

![Uploading timeline.gif…]()

**Comment by zerocrates** [comment]
When I looked at the initial problem here briefly, it seemed the issue was something basically hijacking the events for the clicks on the buttons. The changes you see to the cursor and DOM are a result of the click falling through to the background layer and being interpreted as the start of a "drag" between images.

I didn't quite track it down, whatever's eating those events, but it's believable that it would affect the timeline also.

**Comment by allanaaa** [comment]
Right. Thanks Roy has some unique sidebar behaviour amongst the other themes so I wonder if it's in there.

**Comment by zerocrates** [comment]
It's interesting they both do the same disappearing thing... my best guess would be that probably indicates that it's the "mouseup" event that's getting consumed here. I didn't find it immediately last time but I'll look some more.

The "megamenu" and nav in general was my first area of suspicion for sure.
